import Head from "next/head";
import SEO from "../../components/SEO";
import { productJsonLd, breadcrumbJsonLd } from "../../lib/seo";
import Link from "next/link";
import { shekel } from "../../lib/format";
import { useEffect, useMemo, useState } from "react";
import { useCart } from "../../components/CartContext";
import Header from "../../components/Header";
import ProductCard from "../../components/ProductCard";
import ProductGallery from "../../components/ProductGallery";
import { useLang } from "../../components/LanguageContext";

export async function getServerSideProps({ params }) {
  const { readJson, siteUrl } = await import("../../lib/serverData");
  const products = readJson("products");
  const categories = readJson("categories");
  const found = products.find(p => p.id === params.id || p.slug === params.id);
  if (!found) return { notFound: true };

  const parent = found.autoGeneratedFrom ? (products.find(p => p.id === found.autoGeneratedFrom) || found) : found;
  const product = found.autoGeneratedFrom ? { ...parent, ...found, baseName: parent.name, colorVariants: parent.colorVariants || [], sizeVariants: parent.sizeVariants || [], description: parent.description, shortDescription: parent.shortDescription, reviews: parent.reviews || [], categoryId: parent.categoryId, categoryIds: parent.categoryIds || [] } : found;
  const canonical = `${siteUrl()}/product/${found.id}`;
  const related = products.filter(p => (p.categoryId === product.categoryId || (Array.isArray(p.categoryIds) && p.categoryIds.includes(product.categoryId))) && p.id !== found.id).slice(0, 30);
  return { props: { product, related, category: categories.find(c => c.id === product.categoryId) || null, categories, content: readJson("content"), cms: readJson("pagesCms"), canonical } };
}

function productUrgency(product, t){
  if(Number(product.stock) <= 0) return t("outOfStock");
  if(product.urgentText) return product.urgentText;
  if(product.showStockUrgency === false) return "";
  if(Number(product.stock) === 1) return t("lastStock");
  if(Number(product.stock) <= 3) return t("limitedStock");
  return "";
}

export default function Product({ product, related = [], category, categories, content, cms, canonical }) {
  const { translateProduct, translateCategory, translateText, t } = useLang();
  const tProduct = translateProduct(product);
  const tCategory = translateCategory(category);
  const tRelated = related.map(translateProduct);
  const colorVariants = Array.isArray(product.colorVariants) ? product.colorVariants.filter(v=>v && (v.colorName || v.image || v.images?.length)) : [];
  const sizeVariants = Array.isArray(product.sizeVariants) ? product.sizeVariants.filter(v=>v && v.label) : [];
  const initialColorIndex = Math.max(0, colorVariants.findIndex(v => v?.colorName === product.selectedVariant?.color || v?.colorName === product.color));
  const initialSizeIndex = Math.max(0, sizeVariants.findIndex(v => v?.label === product.selectedVariant?.size || v?.label === product.size));
  const [selectedColorIndex,setSelectedColorIndex] = useState(initialColorIndex);
  const [selectedSizeIndex,setSelectedSizeIndex] = useState(initialSizeIndex);
  const selectedColor = colorVariants[selectedColorIndex] || null;
  const selectedSize = sizeVariants[selectedSizeIndex] || null;
  const sizeBadge =
selectedSize?.label?.includes("20")
? "✈️ מתאים לעלייה למטוס"

: selectedSize?.label?.includes("24")
? "🔥 הגודל המושלם לשבוע חופשה"

: selectedSize?.label?.includes("28")
? "🧳 מתאים עד 23 ק״ג"

: selectedSize?.label?.includes("3")
? "💎 סט 3 מזוודות במחיר מיוחד"

: "";
  const selectedImages = selectedColor ? (selectedColor.images?.length ? selectedColor.images : [selectedColor.image].filter(Boolean)) : [];
  const displayImages = selectedImages.length ? [...selectedImages, ...((product.images||[]).filter(x=>!selectedImages.includes(x)))] : (product.images?.length ? product.images : [product.image].filter(Boolean));
  const baseDisplayName = product.baseName || (product.autoGeneratedFrom ? (product.name || "").replace(new RegExp(`\\s*-?\\s*${product.color || ""}\\s*${product.size || ""}$`.trim(), "i"), "") : tProduct.name);
  const displayName = [baseDisplayName || tProduct.name, selectedColor?.colorName, selectedSize?.label].filter(Boolean).join(" - ");
  const hasValue = (v) => v !== undefined && v !== null && v !== "" && !Number.isNaN(Number(v));
  const selectedPrice = Number(hasValue(selectedSize?.price) ? selectedSize.price : (hasValue(selectedColor?.price) ? selectedColor.price : product.price));
  const selectedOldPrice = Number(hasValue(selectedSize?.oldPrice) ? selectedSize.oldPrice : (hasValue(selectedColor?.oldPrice) ? selectedColor.oldPrice : product.oldPrice));
  const variantStock = Number(selectedSize?.stock ?? selectedColor?.stock ?? product.stock ?? 0);
  const galleryProduct = {...tProduct, name:displayName, price:selectedPrice, oldPrice:selectedOldPrice, image:displayImages[0] || tProduct.image, images:displayImages};

  const cart = useCart();
  useEffect(() => { cart?.registerProducts([product, ...related]); }, [product, related]);

  function addToCart() {
    if(colorVariants.length && !selectedColor) return alert("נא לבחור צבע");
    if(sizeVariants.length && !selectedSize) return alert("נא לבחור מידה");
    cart.add({...product, name:baseDisplayName || product.name}, 1, {
      color:selectedColor?.colorName || "",
      colorHex:selectedColor?.colorHex || "",
      size:selectedSize?.label || "",
      image:displayImages[0] || product.image,
      price:selectedPrice,
      oldPrice:selectedOldPrice,
      stock:variantStock,
      variantLabel:[selectedColor?.colorName, selectedSize?.label].filter(Boolean).join(" / "),
      variantKey:[product.autoGeneratedFrom || product.parentProductId || product.id, selectedColor?.colorName, selectedSize?.label].filter(Boolean).join("__")
    });
  }


  return (
    <>
      <SEO title={tProduct.seoTitle || `${tProduct.name} | NABET PARIS`} description={tProduct.seoDescription || tProduct.shortDescription} canonical={`/product/${product.id}`} image={(product.images && product.images[0]) || product.image} type="product" jsonLd={{"@context":"https://schema.org","@graph":[productJsonLd(tProduct, tCategory), breadcrumbJsonLd([{name:"בית",url:"/"},{name:tCategory?.name || t("products"),url:`/category/${category?.id || ""}`},{name:tProduct.name,url:`/product/${product.id}`}])]}} />

      <Header categories={categories} content={content} cms={cms} />

      <main className="productPage">
        <ProductGallery key={(displayImages[0]||product.image||"")+displayName} product={galleryProduct} />
        <div className="productInfo">
          <Link href={`/category/${category?.id || ""}`} className="mini">{tCategory?.name}</Link>
          <h1>{displayName}</h1>
          <div className="productRatingBlock">
          <span>★★★★★</span>
          <b>{product.rating || 5}/5</b>
          <em>{product.reviewCount || 50} {t("reviews")}</em>
        </div>
        <p className="lead">{tProduct.shortDescription}</p>
        {sizeBadge && (
          <div className="sizePremiumBadge">
            {sizeBadge}
          </div>
        )}
        {selectedColor?.colorName && <div className="productColorBadge">{t("color")}: {selectedColor.colorName}</div>}
        <div className="galleryTrustLine">{translateText("✓ כמה תמונות מוצר  ✓ זום להגדלה  ✓ קנייה בטוחה")}</div>
          <div className="priceUrgencyRow">
            <div>
              <div className="prices big"><b>{shekel(selectedPrice)}</b>{selectedOldPrice ? <span>{shekel(selectedOldPrice)}</span> : null}</div>
              {productUrgency(tProduct, t) && <p className="productUrgencyBig">{productUrgency(tProduct, t)}</p>}
            </div>
<button
  onClick={addToCart}
  disabled={variantStock <= 0}
  className="buy urgentBuyPulse"
>
  🛒 הוספה לעגלה
</button>


          {colorVariants.length > 0 && <div className="variantBlock"><h3>בחרו צבע</h3><div className="colorSwatches">{colorVariants.map((v,i)=><button key={i} type="button" className={i===selectedColorIndex?"selected":""} onClick={()=>setSelectedColorIndex(i)} title={v.colorName}><span style={{background:v.colorHex||"#ddd"}}></span><em>{v.colorName}</em></button>)}</div></div>}
          {sizeVariants.length > 0 && <div className="variantBlock"><h3>בחרו מידה</h3><div className="sizeChips proSizeChips">{sizeVariants.map((v,i)=><button key={i} type="button" className={i===selectedSizeIndex?"selected":""} onClick={()=>setSelectedSizeIndex(i)}><strong>{v.label}</strong>{v.description && <small>{v.description}</small>}{hasValue(v.price) && <em>{shekel(v.price)}</em>}</button>)}</div></div>}
        <div className="multiBuyPromo">
          <b>{t("discount2")}</b>
          <span>{translateText("בקנייה של 2 מוצרים או יותר — הזדמנות מושלמת להוסיף עוד פריט לעגלה.")}</span>
        </div>
          <p>{tProduct.description}</p>

<div className="fastBuyBox">
  <button className="applePayBtn" onClick={addToCart}>
    <img src="/apple-pay.svg" alt="Apple Pay" />
  </button>

  <button className="googlePayBtn" onClick={addToCart}>
    <img src="/google-pay.svg" alt="Google Pay" />
  </button>

  <button className="bitBtn" onClick={addToCart}>
    <img src="/bit-logo.svg" alt="bit" />
  </button>

  <p className="expressShippingNote">
    🚚 המשך מהיר לתשלום מאובטח דרך העגלה
  </p>
</div>          </div>
          <p className="stock">{translateText("נשארו במלאי")}: {variantStock}</p>
        </div>
      </main>

      <section className="reviewsSection">
        <div className="sectionTitle">
          <span>NABET PARIS</span>
          <h2>{translateText("לקוחות ממליצים")}</h2>
          <p>{translateText("ביקורות אמיתיות בסגנון קצר וברור שנותנות ביטחון לפני רכישה.")}</p>
        </div>
        <div className="reviewsGrid">
          {(product.reviews || []).map((r, i) => (
            <article key={i} className="reviewCard">
              <div className="reviewStars">★★★★★</div>
              <b>{r.name}</b>
              <p>{translateText(r.text)}</p>
            </article>
          ))}
        </div>
      </section>

      {related.length > 0 && (
        <section className="relatedProductsSection">
          <div className="sectionTitle">
            <span>{translateText("מומלץ להוסיף")}</span>
            <h2>{translateText("מוצרים שמתאימים לקנייה יחד")}</h2>
            <p>{translateText("בקניית 2 מוצרים או יותר תקבלו 10% הנחה נוספת — כדאי להוסיף עוד מוצר לעגלה.")}</p>
          </div>
          <div className="relatedCarousel">
            {tRelated.map(p => <ProductCard key={p.id} p={p} cat={tCategory} />)}
          </div>
        </section>
      )}
    </>
  );
}
