import { readJson, writeJson } from "../../../../lib/serverData";
import { normalizeProduct, upsertProductWithVariants } from "../../../../lib/productVariants";

function check(req){ return req.headers["x-admin-token"] === (process.env.ADMIN_PASSWORD || readJson("settings").adminPassword || "nabet123"); }

export default function handler(req,res){
  if(!check(req)) return res.status(401).json({error:"אין הרשאה"});
  const { id } = req.query;
  let products = readJson("products");

  if(req.method === "PUT"){
    const existing = products.find(p => p.id === id) || {};
    if(!existing.id) return res.status(404).json({error:"not found"});
    const updated = normalizeProduct({ ...existing, ...req.body, id });
    const nextProducts = upsertProductWithVariants(products, updated);
    writeJson("products", nextProducts);
    return res.json({ ok:true, generated: nextProducts.filter(x=>x.autoGeneratedFrom === id).length });
  }

  if(req.method === "DELETE"){
    products = products.filter(p => p.id !== id && p.autoGeneratedFrom !== id);
    writeJson("products", products);
    return res.json({ok:true});
  }

  return res.status(405).end();
}
