import { readJson, writeJson } from "../../../../lib/serverData";
import { normalizeProduct, upsertProductWithVariants } from "../../../../lib/productVariants";

function check(req){ return req.headers["x-admin-token"] === (process.env.ADMIN_PASSWORD || readJson("settings").adminPassword || "nabet123"); }
function slug(s){ return String(s||"").trim().replace(/[^\p{L}\p{N}]+/gu,"-").replace(/^-|-$/g,"") || Date.now().toString(); }

export default function handler(req,res){
  if(!check(req)) return res.status(401).json({error:"אין הרשאה"});
  if(req.method === "POST"){
    const products = readJson("products");
    const p = normalizeProduct({ ...req.body });
    p.id = p.id || slug(p.name);
    p.slug = p.slug || slug(p.name);
    const nextProducts = upsertProductWithVariants(products, p);
    writeJson("products", nextProducts);
    return res.json({ ok:true, product:p, generated: nextProducts.filter(x=>x.autoGeneratedFrom === p.id).length });
  }
  return res.status(405).end();
}
