function slugify(value){
  return String(value || "")
    .trim()
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\p{L}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/g, "") || "variant";
}

function hasValue(v){
  return v !== undefined && v !== null && v !== "" && !Number.isNaN(Number(v));
}

function money(v, fallback){
  return Number(hasValue(v) ? v : (fallback || 0));
}

function stockValue(v, fallback){
  return Number(hasValue(v) ? v : (fallback || 0));
}

function cleanColorVariants(list){
  return Array.isArray(list)
    ? list.filter(v => v && (v.colorName || v.label || v.image || (Array.isArray(v.images) && v.images.length)))
    : [];
}

function cleanSizeVariants(list){
  return Array.isArray(list)
    ? list.filter(v => v && (v.label || v.description || hasValue(v.price) || hasValue(v.stock)))
    : [];
}

export function normalizeProduct(product){
  const out = { ...(product || {}) };
  out.categoryIds = Array.isArray(out.categoryIds) && out.categoryIds.length ? out.categoryIds : (out.categoryId ? [out.categoryId] : []);
  out.categoryId = out.categoryIds[0] || out.categoryId || "";
  out.colorVariants = cleanColorVariants(out.colorVariants);
  out.sizeVariants = cleanSizeVariants(out.sizeVariants);
  if(!out.createdAt) out.createdAt = new Date().toISOString();
  out.updatedAt = new Date().toISOString();
  out.price = money(out.price, 0);
  out.oldPrice = money(out.oldPrice, 0);
  out.stock = stockValue(out.stock, 0);
  return out;
}

function variantImages(color, product){
  const imgs = color ? ((Array.isArray(color.images) && color.images.length ? color.images : [color.image].filter(Boolean))) : [];
  if(imgs.length) return imgs;
  if(Array.isArray(product.images) && product.images.length) return product.images;
  return [product.image || "/products/placeholder-wallet.svg"].filter(Boolean);
}

function buildShortcut(parent, color, size, previous){
  const product = normalizeProduct(parent);
  const colorName = color?.colorName || "";
  const sizeName = size?.label || "";
  const suffix = [colorName, sizeName].filter(Boolean).join(" ");
  const id = `${product.id}--${slugify(suffix)}`;
  const imgs = variantImages(color, product);
  const image = imgs[0] || product.image || "/products/placeholder-wallet.svg";
  const price = money(size?.price, money(color?.price, product.price));
  const oldPrice = money(size?.oldPrice, money(color?.oldPrice, product.oldPrice));
  const stock = stockValue(size?.stock, stockValue(color?.stock, product.stock));

  return {
    ...product,
    ...(previous || {}),
    id,
    slug: id,
    name: `${product.name || "Produit"} ${suffix}`.trim(),
    baseName: product.name || "Produit",
    seoTitle: `${product.name || "Produit"} ${suffix} | NABET PARIS`.trim(),
    seoDescription: product.seoDescription || product.shortDescription || product.description || "",
    image,
    images: imgs,
    price,
    oldPrice,
    stock,
    color: colorName,
    size: sizeName,
    selectedVariant: {
      color: colorName,
      size: sizeName,
      colorHex: color?.colorHex || "",
      image,
      price,
      oldPrice,
      stock
    },
    isCatalogShortcut: true,
    isAutoVariant: true,
    autoGeneratedFrom: product.id,
    parentProductId: product.id,
    createdAt: previous?.createdAt || new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };
}

export function generateVariantProducts(parent, existingProducts = []){
  const product = normalizeProduct(parent);
  if(product.isAutoVariant || product.autoGeneratedFrom || product.isCatalogShortcut) return [];

  const colors = product.colorVariants.length ? product.colorVariants : [null];
  const sizes = product.sizeVariants.length ? product.sizeVariants : [null];
  const previousById = new Map(existingProducts.filter(p => p.autoGeneratedFrom === product.id).map(p => [p.id, p]));
  const generated = [];

  for(const color of colors){
    for(const size of sizes){
      if(!color && !size) continue;
      const suffix = [color?.colorName || "", size?.label || ""].filter(Boolean).join(" ");
      const id = `${product.id}--${slugify(suffix)}`;
      generated.push(buildShortcut(product, color, size, previousById.get(id)));
    }
  }
  return generated;
}

export function upsertProductWithVariants(products, inputProduct){
  const product = normalizeProduct(inputProduct);
  const masterId = product.autoGeneratedFrom || product.parentProductId || product.id;
  const withoutParentAndGenerated = products.filter(p => p.id !== masterId && p.id !== product.id && p.autoGeneratedFrom !== masterId);
  const masterProduct = product.autoGeneratedFrom
    ? normalizeProduct({ ...(products.find(p => p.id === masterId) || product), ...product, id: masterId, autoGeneratedFrom: undefined, isAutoVariant: false, isCatalogShortcut: false })
    : product;
  const generated = generateVariantProducts(masterProduct, products);
  return [masterProduct, ...generated, ...withoutParentAndGenerated];
}
