import SEO from "../components/SEO";
import { organizationJsonLd, websiteJsonLd } from "../lib/seo";
import { useEffect, useMemo, useState } from "react";
import { readJson, siteUrl } from "../lib/serverData";
import Header from "../components/Header";
import ProductCard from "../components/ProductCard";
import DynamicSections from "../components/DynamicSections";
import SiteFooter from "../components/SiteFooter";
import { useCart } from "../components/CartContext";
import { useLang } from "../components/LanguageContext";

const INITIAL_PER_CATEGORY = 8;
const STEP_PER_CATEGORY = 8;

function lightProduct(p){
  const firstImage = (Array.isArray(p.images) && p.images[0]) || p.image || "/products/placeholder-wallet.svg";
  return {
    id:p.id,
    slug:p.slug,
    name:p.name,
    price:p.price,
    oldPrice:p.oldPrice,
    stock:p.stock,
    image:firstImage,
    images:firstImage ? [firstImage] : [],
    categoryId:p.categoryId || "",
    categoryIds:Array.isArray(p.categoryIds) ? p.categoryIds : (p.categoryId ? [p.categoryId] : []),
    badge:p.badge || "",
    urgentText:p.urgentText || "",
    showStockUrgency:p.showStockUrgency,
    color:p.color || "",
    size:p.size || "",
    shortDescription:p.shortDescription || "",
    rating:p.rating || 5,
    reviewCount:p.reviewCount || 36,
    createdAt:p.createdAt || "",
    updatedAt:p.updatedAt || "",
    autoGeneratedFrom:p.autoGeneratedFrom || "",
    isAutoVariant:!!p.isAutoVariant
  };
}

export async function getServerSideProps() {
  const rawProducts = readJson("products");
  const products = rawProducts
    .map(lightProduct)
    .sort((a,b)=> new Date(b.createdAt || b.updatedAt || 0) - new Date(a.createdAt || a.updatedAt || 0));
  const categories = readJson("categories").sort((a,b)=>(a.order||0)-(b.order||0));
  const cms = readJson("pagesCms");
  return { props: { products, categories, content: readJson("content"), settings: readJson("settings"), cms, canonical: siteUrl() } };
}

function productInCategory(product, categoryId){
  const ids = Array.isArray(product.categoryIds) ? product.categoryIds : [];
  return product.categoryId === categoryId || ids.includes(categoryId);
}

function CategoryShelf({ category, products, translateProduct, t }){
  const [visible, setVisible] = useState(INITIAL_PER_CATEGORY);
  const shown = products.slice(0, visible).map(translateProduct);
  if(!products.length) return null;

  const shuffledProducts = [...products].sort(() => Math.random() - 0.5);

return (
    <section className="section categoryShelf" id={`cat-${category.id}`}>
      <div className="sectionHead">
        <div>
          <span className="mini">NABET PARIS</span>
          <h2>{category.name}</h2>
        </div>
      </div>
      <div className="grid">
        {shown.map(p => <ProductCard key={p.id} p={p} cat={category} />)}
      </div>
      {visible < products.length && (
        <div className="loadMoreWrap">
          <button className="loadMoreBtn" onClick={()=>setVisible(v=>v+STEP_PER_CATEGORY)}>
            {"לצפייה בעוד מוצרים"}
          </button>
        </div>
      )}
    </section>
  );
}

export default function Home({ products, categories, content, settings, cms }) {
  const cart = useCart();
  const { t, translateProduct, translateSections, translateText } = useLang();
  useEffect(() => { cart?.registerProducts(products); }, [products]);

  const home = cms.home || {};
  const translatedSections = translateSections(home.sections || []);
  const shelves = useMemo(() => categories.map(category => ({
    category,
    products: products.filter(p => productInCategory(p, category.id))
  })).filter(s => s.products.length), [categories, products]);

  return (
    <>
      <SEO title={home.seoTitle || settings.seoTitle} description={home.seoDescription || settings.seoDescription} canonical="/" image="/logo-nabet.png" keywords={settings.seoKeywords} jsonLd={{"@context":"https://schema.org","@graph":[organizationJsonLd(), websiteJsonLd()]}} />

      <Header categories={categories} content={content} cms={cms} />
      <main>
        <DynamicSections sections={translatedSections} />

        <section id="products" className="section homeIntroProducts">
          <div className="sectionHead">
            <div><span className="mini">{t("collection")}</span><h2>{translateText(content.collectionTitle) || t("products")}</h2></div>
          </div>
        </section>

        {shelves.map(({category, products}) => (
          <CategoryShelf key={category.id} category={category} products={products} translateProduct={translateProduct} t={t} />
        ))}
      </main>
      <SiteFooter cms={cms} />
    </>
  );
}
